SalsaVerde/orders/urls.py
from django.urls import path

from SalsaVerde.common.views import DeleteObjectView
from SalsaVerde.orders.models import PackageTemplate
from SalsaVerde.orders.views import shopify
from SalsaVerde.orders.views.common import order_details, orders_list, update_packed_product
from SalsaVerde.orders.views.dhl import dhl_order_create
from SalsaVerde.orders.views.express_freight import ef_order_create
from SalsaVerde.orders.views.setup import package_temp_add, package_temp_details, package_temp_edit, package_temp_list

urlpatterns = [
    path('', orders_list, name='orders-list'),
    path('<int:pk>/', order_details, name='order-details'),
    path('<int:pk>/update-product', update_packed_product, name='order-packed-product'),
    path('setup/package-temp/', package_temp_list, name='package-temps'),
    path('setup/package-temp/add/', package_temp_add, name='package-temps-add'),
    path('setup/package-temp/<int:pk>/', package_temp_details, name='package-temps-details'),
    path('setup/package-temp/<int:pk>/edit/', package_temp_edit, name='package-temps-edit'),
    path(
        'setup/package-temp/<int:pk>/delete/',
        DeleteObjectView.as_view(model=PackageTemplate),
        name='package-temps-delete',
    ),
    path('<int:pk>/fulfill/express/', ef_order_create, name='fulfill-order-ef'),
    path('<int:pk>/fulfill/dhl/', dhl_order_create, name='fulfill-order-dhl'),
    path('shopify/callback/', shopify.callback, name='shopify-callback'),
]

SalsaVerde/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include, path

from SalsaVerde.common.views import dashboard, login

urlpatterns = [
    path('', dashboard, name='index'),
    path('login/', login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='base.jinja'), name='logout'),
    path('', include('SalsaVerde.company.urls')),
    path('orders/', include('SalsaVerde.orders.urls')),
    path('stock/', include('SalsaVerde.stock.urls')),
]


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

SalsaVerde/main/models.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.postgres.forms import JSONField
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe

from SalsaVerde.storage_backends import PrivateMediaStorage


class Company(models.Model):
    name = models.CharField('Name', max_length=255)
    website = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name


class CompanyQueryset(QuerySet):
    def request_qs(self, request):
        return self.filter(company=request.user.company)


class NoQS(QuerySet):
    def request_qs(self, request):
        raise NotImplementedError


class BaseModel(models.Model):
    objects = NoQS.as_manager()

    class Meta:
        abstract = True


class CompanyNameBaseModel(BaseModel):
    name = models.CharField('Name', max_length=255)
    company = models.ForeignKey(Company, verbose_name='Company', on_delete=models.CASCADE)
    objects = CompanyQueryset.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class UserManager(BaseUserManager):
    def _create_user(self, email, company, password, is_superuser=False, **extra_fields):
        """Create and save a User with the given email and password."""
        email = self.normalize_email(email)
        user = self.model(email=email, is_superuser=is_superuser, company=company, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, company, password=None, **extra_fields):
        return self._create_user(email, company, password, **extra_fields)

    def create_superuser(self, email, company, password, **extra_fields):
        return self.create_superuser(email, company, password, is_superuser=True, **extra_fields)


class User(AbstractUser):
    objects = UserManager.from_queryset(CompanyQueryset)()

    company = models.ForeignKey(Company, verbose_name='Company', on_delete=models.CASCADE)

    username = None
    email = models.EmailField('Email Address', unique=True)
    first_name = models.CharField('First name', max_length=30, blank=True)
    last_name = models.CharField('Last name', max_length=150, blank=True)
    last_logged_in = models.DateTimeField('Last Logged in', default=datetime(2018, 1, 1, tzinfo=timezone.utc))
    street = models.TextField('Street Address', null=True, blank=True)
    town = models.CharField('Town', max_length=50, null=True, blank=True)
    country = models.CharField('Country', max_length=50, null=True, blank=True)
    postcode = models.CharField('Postcode', max_length=20, null=True, blank=True)
    phone = models.CharField('Phone', max_length=255, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def has_document(self, doc_type):
        return self.focused_documents.filter(doc_type=doc_type).exists()

    def display_name(self):
        return str(self)

    def display_address(self):
        address = [a for a in [self.street, self.town, self.postcode, self.country] if a]
        return ', '.join(address) or '–'

    def get_absolute_url(self):
        return reverse('users-details', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @staticmethod
    def prefix():
        return 'users'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'


class Supplier(CompanyNameBaseModel):
    street = models.TextField('Street Address', null=True, blank=True)
    town = models.CharField('Town', max_length=50, null=True, blank=True)
    county = models.CharField('County', max_length=50, null=True, blank=True)
    country = models.CharField('Country', max_length=50, null=True, blank=True)
    postcode = models.CharField('Postcode', max_length=20, null=True, blank=True)
    phone = models.CharField('Phone', max_length=255, null=True, blank=True)
    email = models.EmailField('Email', max_length=65, null=True, blank=True)
    main_contact = models.CharField('Main Contact', max_length=50, null=True, blank=True)
    contact_phone = models.CharField('Contact Phone', max_length=255, null=True, blank=True)
    vat_number = models.CharField('VAT Number', max_length=50, null=True, blank=True)
    company_number = models.CharField('Company Number', max_length=50, null=True, blank=True)

    def display_email(self):
        if self.email:
            return mark_safe(f'<a href="mailto:{self.email}">{self.email}</a>')
        return '–'

    def display_phone(self):
        if self.phone:
            return mark_safe(f'<a href="tel:{self.phone}">{self.phone}</a>')
        return '–'

    def display_address(self):
        address = [a for a in [self.street, self.town, self.postcode, self.country] if a]
        return ', '.join(address) or '–'

    @staticmethod
    def prefix():
        return 'suppliers'

    def get_absolute_url(self):
        return reverse('suppliers-details', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Supplier'
        verbose_name_plural = 'Suppliers'


class IngredientType(CompanyNameBaseModel):
    UNIT_KILO = 'kilogram'
    UNIT_LITRE = 'litre'
    UNIT_TYPES = (
        (UNIT_KILO, 'kg'),
        (UNIT_LITRE, 'litre'),
    )
    unit = models.CharField('Units', max_length=25, choices=UNIT_TYPES, help_text='Ingredient is measured in?')

    @classmethod
    def prefix(cls):
        return 'ingredient-types'

    def get_absolute_url(self):
        return reverse('ingredient-types-details', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Ingredient Type'
        verbose_name_plural = 'Ingredients Types'


class IngredientQuerySet(QuerySet):
    def request_qs(self, request):
        return self.filter(ingredient_type__company=request.user.company)


class Ingredient(BaseModel):
    ingredient_type = models.ForeignKey(
        IngredientType, verbose_name='Ingredient Type', related_name='ingredients', on_delete=models.CASCADE
    )
    batch_code = models.CharField('Batch Code', max_length=25)
    condition = models.CharField('Condition', max_length=25, default='Good')
    supplier = models.ForeignKey(
        Supplier, verbose_name='Supplier', related_name='ingredients', null=True, on_delete=models.SET_NULL
    )
    intake_quality_check = models.BooleanField('Accept goods', default=False)
    intake_quality_check.help_text = 'Goods are free from damage and pests'
    quantity = models.DecimalField('Quantity', max_digits=25, decimal_places=3)
    goods_intake = models.ForeignKey(
        'main.GoodsIntake', related_name='ingredients', verbose_name='Goods Intake', on_delete=models.CASCADE
    )
    finished = models.BooleanField('Finished', default=False)
    objects = IngredientQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('ingredients-details', kwargs={'pk': self.pk})

    def display_quantity(self):
        return f'{round(self.quantity, 3)} {dict(IngredientType.UNIT_TYPES)[self.ingredient_type.unit]}'

    def __str__(self):
        return mark_safe(f'{self.name} - {self.batch_code}')

    @property
    def name(self):
        return self.ingredient_type.name

    @property
    def intake_document(self):
        return self.goods_intake.intake_document

    @classmethod
    def intake_document_type(cls):
        return Document.FORM_SUP01

    @classmethod
    def prefix(cls):
        return 'ingredients'

    class Meta:
        ordering = ('ingredient_type__name',)
        verbose_name = 'Ingredient'
        verbose_name_plural = 'Ingredients'


class ContainerType(CompanyNameBaseModel):
    TYPE_BOTTLE = 'bottle'
    TYPE_CAP = 'cap'
    TYPE_OTHER = 'other'
    TYPE_CONTAINERS = (
        (TYPE_BOTTLE, 'Bottle'),
        (TYPE_CAP, 'Cap'),
        (TYPE_OTHER, 'Container'),
    )
    size = models.DecimalField('Size', max_digits=25, null=True, blank=True, decimal_places=3)
    type = models.CharField('Container Type', choices=TYPE_CONTAINERS, max_length=255, default=TYPE_BOTTLE)

    @classmethod
    def prefix(cls):
        return 'container-types'

    def get_absolute_url(self):
        return reverse('container-types-details', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Container Type'
        verbose_name_plural = 'Container Types'


class ContainerQuerySet(QuerySet):
    def request_qs(self, request):
        return self.filter(container_type__company=request.user.company)


class Container(BaseModel):
    objects = ContainerQuerySet.as_manager()

    container_type = models.ForeignKey(
        ContainerType, verbose_name='Container', related_name='containers', on_delete=models.CASCADE
    )
    batch_code = models.CharField('Batch Code', max_length=25)
    condition = models.CharField('Condition', max_length=25, default='Good')
    supplier = models.ForeignKey(
        Supplier, verbose_name='Supplier', related_name='containers', null=True, on_delete=models.SET_NULL
    )
    intake_quality_check = models.BooleanField('Accept goods', default=False)
    intake_quality_check.help_text = 'Goods are free from damage and pests'
    quantity = models.DecimalField('Quantity', max_digits=25, decimal_places=3)
    goods_intake = models.ForeignKey(
        'main.GoodsIntake', related_name='containers', verbose_name='Goods Intake', on_delete=models.CASCADE
    )
    finished = models.BooleanField('Finished', default=False)

    @classmethod
    def prefix(cls):
        return 'containers'

    def get_absolute_url(self):
        return reverse('containers-details', kwargs={'pk': self.pk})

    def __str__(self):
        return mark_safe(f'{self.name} - {self.batch_code}')

    @property
    def intake_document(self):

SalsaVerde/orders/models.py
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse

from SalsaVerde.company.models import Company, CompanyNameBaseModel, CompanyQueryset, User
from SalsaVerde.stock.models import Product


class Order(models.Model):
    DHL_CARRIER = 'dhl'
    EF_CARRIER = 'expressfreight'
    CARRIER_CHOICES = (
        (DHL_CARRIER, 'DHL'),
        (DHL_CARRIER, 'ExpressFreight'),
    )
    STATUS_UNFULFILLED = 'unfulfilled'
    STATUS_FULFILLED = 'fulfilled'
    STATUS_CANCELLED = 'cancelled'
    STATUS_CHOICES = (
        (STATUS_UNFULFILLED, 'Unfulfilled'),
        (STATUS_FULFILLED, 'Fulfilled'),
        (STATUS_CANCELLED, 'Cancelled/Deleted'),
    )

    objects = CompanyQueryset.as_manager()

    created = models.DateTimeField('Created', auto_now_add=True, db_index=True)
    shipping_id = models.CharField(max_length=255, null=True, blank=True)
    shopify_id = models.CharField(max_length=255, null=True, blank=True, unique=True)
    tracking_url = models.CharField(max_length=255, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_CHOICES, default=STATUS_UNFULFILLED, max_length=120)
    shipment_details = models.JSONField(blank=True, null=True)
    carrier = models.CharField(choices=CARRIER_CHOICES, max_length=20, null=True, blank=True)
    extra_data = models.JSONField(blank=True, null=True, default=dict)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    @classmethod
    def prefix(cls):
        return 'orders'

    def get_absolute_url(self):
        return reverse('order-details', kwargs={'pk': self.id})

    def __str__(self):
        return f'Order {self.shopify_id or self.id}'

    class Meta:
        ordering = ('-created',)


class PackageTemplate(CompanyNameBaseModel):
    width = models.DecimalField(verbose_name='Width (cm)', decimal_places=2, max_digits=6)
    length = models.DecimalField(verbose_name='Length (cm)', decimal_places=2, max_digits=6)
    height = models.DecimalField(verbose_name='Height (cm)', decimal_places=2, max_digits=6)
    weight = models.DecimalField(verbose_name='Weight (kg)', decimal_places=2, max_digits=6, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('package-temps-details', kwargs={'pk': self.pk})

    @classmethod
    def prefix(cls):
        return 'package-temps'

    class Meta:
        ordering = ('name',)
        verbose_name = 'Package Template'
        verbose_name_plural = 'Package Templates'


class ProductOrderQueryset(QuerySet):
    def request_qs(self, request):
        return self.filter(order__company=request.user.company)


class ProductOrder(models.Model):
    objects = ProductOrderQueryset.as_manager()
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders')

SalsaVerde/orders/forms/setup.py
from SalsaVerde.orders.models import PackageTemplate
from SalsaVerde.stock.forms.base_forms import SVModelForm


class UpdatePackageTemplateForm(SVModelForm):
    class Meta:
        model = PackageTemplate
        exclude = {'company'}

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.company = self.request.user.company
        return super().save(commit)

SalsaVerde/stock/forms/documents.py
from django.shortcuts import get_object_or_404

from SalsaVerde.company.models import User
from SalsaVerde.stock.forms.base_forms import SVModelForm
from SalsaVerde.stock.models import Document, Supplier


class UpdateDocumentForm(SVModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.pk:
            self.fields['author'].initial = self.request.user
            self.fields['file'].required = False
        if self.request.GET.get('supplier'):
            sup = get_object_or_404(Supplier.objects.request_qs(self.request), pk=self.request.GET['supplier'])
            self.fields['supplier'].initial = sup
        if self.request.GET.get('focus'):
            user = get_object_or_404(User.objects.request_qs(self.request), pk=self.request.GET['focus'])
            self.fields['focus'].initial = user

    class Meta:
        model = Document
        exclude = {'edits', 'date_created'}

SalsaVerde/orders/views/setup.py
from SalsaVerde.common.views import AddModelView, DetailView, ModelListView, UpdateModelView
from SalsaVerde.orders.forms.setup import UpdatePackageTemplateForm
from SalsaVerde.orders.models import PackageTemplate


class PackageTemplateAdd(AddModelView):
    model = PackageTemplate
    form_class = UpdatePackageTemplateForm


package_temp_add = PackageTemplateAdd.as_view()


class PackageTemplateEdit(UpdateModelView):
    model = PackageTemplate
    form_class = UpdatePackageTemplateForm


package_temp_edit = PackageTemplateEdit.as_view()


class PackageTempDetails(DetailView):
    model = PackageTemplate
    display_items = [
        'name',
        'width',
        'length',
        'height',
    ]


package_temp_details = PackageTempDetails.as_view()


class PackageTempList(ModelListView):
    model = PackageTemplate
    display_items = [
        'name',
        'width',
        'length',
        'height',
    ]
    order_by = 'name'


package_temp_list = PackageTempList.as_view()

templates/add_product_form.jinja
{% extends 'auth.jinja' %}

{% from 'macros.jinja' import spinner %}

{% block content %}
  <div class="row">
    <form method="post" enctype="multipart/form-data">
      {% for _, errors in form.errors.items() %}
        <div class="alert alert-danger">{{ errors[0] }}</div>
      {% endfor %}
      {% csrf_token %}
      <div class="edit-form">
        <div class="row">
          <div class="col">{{ form.product_type | bootstrap }}</div>
          <div class="col">{{ form.batch_code | bootstrap }}</div>
          <div class="col">{{ form.date_of_infusion | bootstrap }}</div>
        </div>
        <div id="product-ingredients" class="mt-4">
          {{ spinner() }}
        </div>
      </div>
      <div class="buttons pt-3">
        <button class="btn btn-primary" type="submit">Save</button>
        <a class="btn btn-secondary" href="{{ view.get_cancel_url() }}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon" type="image/png" href="/static/img/favicon.png" sizes="16x16">
  <title>{% if page.title %}{{ page.title }}{% else %}{{ site.title }}{% endif %}</title>
  <meta name="viewport" content="width=device-width">
  <meta name="description" content="{{ site.description }}">
  {% if site.meta_author %}<meta name="author" content="{{ site.meta_author }}">{% endif %}
  <link rel="alternate" type="application/rss+xml" title="RSS" href="/feed.xml">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <body id="page-top" class="index">
    <div id="page-header"><h1>{{ title }}</h1>{% block nav %}{% endblock %}</div>
    <div id="content">
      {% block content %}{% endblock %}
    </div>
  </body>
  <footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </footer>
</html>

templates/details_view.jinja
{% extends 'auth.jinja' %}

{% from 'macros.jinja' import extra_content_table %}

{% block content %}
  <div class="col-12 pt-3">
    <div class="card item-details">
      <div class="card-header">
        <h5 class="card-title"><span class="fa fa-list"></span>&nbsp;Details</h5>
      </div>
      <div class="card-body">
        <div>
          {% for field_name, v in display_items %}
            <div>
              <label class="text-muted">{{ field_name }}:</label> <span class="display-item">{{ v }}</span>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% if extra_content %}
    {% for obj in extra_content %}
      <div class="pt-3">
        {{ extra_content_table(obj) }}
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

templates/dhl_order_form.jinja
{% extends 'form_view.jinja' %}

{% from 'macros.jinja' import order_details, display_formset with context %}

{% block content %}
  {{ order_details(view.object.extra_data, show_amounts=False) }}
  <form method="post" enctype="multipart/form-data" class="formsets-form custom-form">
    {% csrf_token %}
    {{ form.shopify_order }}
    <div class="form-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Customer</h3>
      </div>
      <div class="row">
        <div class="col-md-6">{{ form.name | bootstrap }}</div>
        <div class="col-md-6">{{ form.phone | bootstrap }}</div>
      </div>
    </div>
    <div class="form-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Delivery Address</h3>
      </div>
      <div class="row">
        <div class="col-md-4">{{ form.first_line | bootstrap }}</div>
        <div class="col-md-4">{{ form.second_line | bootstrap }}</div>
        <div class="col-md-4">{{ form.town | bootstrap }}</div>
        <div class="col-md-4">{{ form.county | bootstrap }}</div>
        <div class="col-md-4">{{ form.postcode | bootstrap }}</div>
        <div class="col-md-4">{{ form.country | bootstrap }}</div>
      </div>
    </div>
    <div class="form-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Packages sending</h3>
      </div>
      <div class="row">
        <div class="col-md-6">{{ form.service_code | bootstrap }}</div>
        <div class="col-md-6">{{ form.dispatch_date | bootstrap }}</div>
        {{ display_formset(package_formset) }}
      </div>
    </div>
    <input type="submit" value="Fulfill order" class="btn btn-outline-primary">
  </form>
  <script>
    window.pack_temp_lu = {{ pack_temp_lu | tojson }};
  </script>
{% endblock %}

templates/edit_product_type_size.jinja
{% extends 'form_view.jinja' %}

{% block submit_buttons %}
  {{ super() }}
  <button class="btn btn-danger pull-right" data-confirm="Are you sure you want to delete this item?" data-method="POST"
          href="{{ url('product-type-sizes-delete', pk=view.object.pk) }}">
    Delete
  </button>
{% endblock %}

templates/ef_order_form.jinja
{% extends 'form_view.jinja' %}

{% from 'macros.jinja' import order_details, display_formset with context %}

{% block content %}
  {{ order_details(view.object.extra_data, show_amounts=False) }}
  <form method="post" enctype="multipart/form-data" class="formsets-form custom-form">
    {% csrf_token %}
    {{ form.shopify_order }}
    <div class="form-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Customer</h3>
      </div>
      <div class="row">
        <div class="col-md-6">{{ form.name | bootstrap }}</div>
        <div class="col-md-6">{{ form.phone | bootstrap }}</div>
      </div>
    </div>
    <div class="form-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Delivery Address</h3>
      </div>
      <div class="row">
        <div class="col-md-12">{{ form.region | bootstrap }}</div>
        <div class="col-md-6">{{ form.first_line | bootstrap }}</div>
        <div class="col-md-6">{{ form.second_line | bootstrap }}</div>
        <div class="col-md-4">{{ form.town | bootstrap }}</div>
        <div class="col-md-4">{{ form.county | bootstrap }}</div>
        <div class="col-md-4">{{ form.postcode | bootstrap }}</div>
      </div>
    </div>
    <div class="form-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Packages sending</h3>
      </div>
      <div class="row">
        <div class="col-xs-12">{{ form.dispatch_date | bootstrap }}</div>
        {{ display_formset(package_formset) }}
      </div>
    </div>
    <input type="submit" value="Fulfill order" class="btn btn-outline-primary">
  </form>
{% endblock %}

{% block extra_js %}
  <script id="ef-form">
    window.ni_counties = {{ ni_counties | safe }}
    window.ie_counties = {{ ie_counties | safe }}
    window.pack_temp_lu = {{ pack_temp_lu | tojson }}
  </script>
{% endblock %}

templates/ingredients-intake.jinja
{% extends formset_form.jinja %}

{% block extra_js %}
  <script>
    const $ingred_type = $('#id_ingredient_type')
    const $quantity = $('#id_quantity')
    $ingred_type.change(() => {
      const val = $ingred_type.val()
      const units_lu = {{ ingred_units_lu | tojson | safe }}
      let units = units_lu[val]
      if (units !== undefined) {
        $quantity.attr('placeholder', units)
      } else {
        $quantity.attr('placeholder', 'Quantity')
      }
    })
    window.ni_counties = {{ ni_counties | safe }}
    window.ie_counties = {{ ie_counties | safe }}
    window.pack_temp_lu = {{ pack_temp_lu | tojson | safe}}
  </script>
{% endblock %}

templates/intake_goods_form.jinja
{% extends 'auth.jinja' %}

{% from 'macros.jinja' import display_formset %}

{% block content %}
  <form method="post" action="" id="formsets-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      {% set col = (12 / form.visible_fields() | length) | string %}
      {% for field in form.visible_fields() %}
        <div class="col-md-{{ col[0] }} unpad">{{ field|bootstrap }}</div>
      {% endfor %}
    </div>
    <div class="row">
      {{ display_formset(formset) }}
    </div>
    <input type="submit" value="{{ _('Submit') }}" class="btn btn-default" />
  </form>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div id="login-block" class="text-center">
      <div>
        <h2>Login</h2>
        <form method="post">
          {% csrf_token %}
          <div id="login-form">
            {{ form.username }}
            {{ form.password }}
            <button type="submit">Login</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/order_list.jinja
{% extends 'auth.jinja' %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <tr>
        <td><b>Order</b></td>
        <td><b>Created</b></td>
        <td><b>Customer</b></td>
        <td><b>Total</b></td>
        <td><b>Status</b></td>
        <td><b>Location</b></td>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{{ url('order-details', pk=order.id) }}">Order #{{ order.id }}{% if order.shopify_id %}({{ order.extra_data.name }}){% endif %}</a>
          </td>
          <td>{{ view.created_at(shopify_order.created_at) }}</td>
          <td>{{ object.extra_data.billing_address.name if object.extra_data.billing_address else 'No billing details' }}</td>
          <td>£{{ object.extra_data.total_price }}</td>
          <td>{{ object.get_status_display() }}</td>
          <td>{{ view.get_location(object.extra_data) or 'No known location' }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/packed_product_form.jinja
{% extends 'auth.jinja' %}

{% from 'macros.jinja' import display_formset, order_details with context %}

{% block content %}
  {% if order_data %}
    {{ order_details(order_data, False) }}
  {% endif %}
  <form method="post" action="" class="formsets-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ display_formset(formset) }}
    <input type="submit" value="Submit" class="btn btn-outline-primary" />
  </form>
{% endblock %}